version: '3'

services:
  nextjs:
    container_name: video_ia_nextjs
    image: node:18-alpine
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://video_ia_user:Thunder23**@mariadb:3306/video_ia_db
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    volumes:
      - ./nextjs:/app
    working_dir: /app
    command: sh -c "apk add --no-cache openssl && npm install --legacy-peer-deps && npx prisma generate && npm run dev"
    networks:
      - video-ia-net
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    container_name: video_ia_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/error-pages:/usr/share/nginx/html
    networks:
      - video-ia-net
    depends_on:
      - nextjs
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  certbot:
    container_name: video_ia_certbot
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email contact@video-ia.net -d video-ia.net -d www.video-ia.net --agree-tos

  mariadb:
    container_name: video_ia_mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: video_ia_db
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/my.cnf:/etc/mysql/my.cnf:ro
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - video-ia-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mariadb_data:

networks:
  video-ia-net:
    driver: bridge